### ISSUE TITLE
Connection to remote host was lost. Stopping instead of restarting

### ISSUE THREAD

**Issue by Mmoo1919** [Geosearchef/placebot#14]
After a while of running the bot, I get an error that stops the program instead of restarting it. Here's the error:

```
Getting board


Error encountered while running bot: Connection to remote host was lost.

Restarting...

Traceback (most recent call last):
  File "src/placebot.py", line 121, in <module>
    raise e
  File "src/placebot.py", line 117, in <module>
    run_bot()
  File "src/placebot.py", line 110, in run_bot
    run_board_watcher_placer(placers)
  File "src/placebot.py", line 70, in run_board_watcher_placer
    placer.update_board()
  File "/mnt/c/users/USERNAME/downloads/placebotnew/placebot/src/placer.py", line 172, in update_board
    self.update_canvas(canvas_id)
  File "/mnt/c/users/USERNAME/downloads/placebotnew/placebot/src/placer.py", line 241, in update_canvas
    temp = json.loads(ws.recv())
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_core.py", line 357, in recv
    opcode, data = self.recv_data()
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_core.py", line 380, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_core.py", line 401, in recv_data_frame
    frame = self.recv_frame()
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_core.py", line 440, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 338, in recv_frame
    self.recv_header()
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 294, in recv_header
    header = self.recv_strict(2)
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_abnf.py", line 373, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_core.py", line 524, in _recv
    return recv(self.sock, bufsize)
  File "/mnt/c/users/USERNAME/downloads/placebotnew/.venv/lib/python3.8/site-packages/websocket/_socket.py", line 122, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
```

**Comment by Geosearchef** [comment]
Please pull the newest version. This is from one where I accidently pushed the raising of the exception when restarting the bot for debug purposes.
