### ISSUE TITLE
Output from console

### ISSUE THREAD

**Issue by GooglesXmaddness** [Geosearchef/placebot#4]
Traceback (most recent call last):
  File "C:\Users\ruadd\Desktop\placebot-main\src\placebot.py", line 6, in <module>
    from placer import Placer
  File "C:\Users\ruadd\Desktop\placebot-main\src\placer.py", line 12, in <module>
    from target_configuration import target_configuration
  File "C:\Users\ruadd\Desktop\placebot-main\src\target_configuration.py", line 6, in <module>
    from local_configuration import local_configuration
  File "C:\Users\ruadd\Desktop\placebot-main\src\local_configuration.py", line 7, in <module>
    local_configuration = json.load(f)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 36 (char 209)

**Comment by GooglesXmaddness** [comment]
{
    "accounts": [
        {"username": "xxxxxx", "password":  "xxxxx"},
        {"username": "xxxxx", "password":  "xxxx"}
    ],
    "target_configuration_url": "C:\Users\ruadd\Desktop\placebot-main\out.cfg"
}

**Comment by GooglesXmaddness** [comment]
what comma

**Comment by Geosearchef** [comment]
Your using backslashes `\`. They are escape characters in json. If you actually want to use a backslash and not escape, you will have to use `\\`.

So use:

```
"target_configuration_url": "C:\\Users\\ruadd\\Desktop\\placebot-main\\out.cfg"
```

**Comment by GooglesXmaddness** [comment]
Thanks alot! now it fully works! However, could I ask for a favor? Could you possibly make a script which would grab accounts data from txt file and put it into config.json atomatically? so login:password would be inputted there automatically.

**Comment by Geosearchef** [comment]
Euhm, why, what's the difference? Isn't config.json literally just a a bit differently formatted text file?

Give writing this yourself a try. You literally just need to read your text file, split the string, create a dictionary with the same structure as config.json and write that to the file as json. Google is your friend :).

**Comment by GooglesXmaddness** [comment]
guacamole
